# This rule is not used by the project fetchfy itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over fetchfy.fetchfy.ai.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fetchfy
    app.kubernetes.io/managed-by: kustomize
  name: gateway-admin-role
rules:
- apiGroups:
  - fetchfy.fetchfy.ai
  resources:
  - gateways
  verbs:
  - '*'
- apiGroups:
  - fetchfy.fetchfy.ai
  resources:
  - gateways/status
  verbs:
  - get
